name: Build and Test SQL-JDBC
on:
  push:
    branches:
      - master
      - opendistro-*

jobs:
  Build-SQL-JDBC:
    strategy:
      matrix:
        java: [13]

    name: Build and Test SQL-JDBC Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SQL-JDBC
        uses: actions/checkout@v1
        
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: Run build
        run: |
          ./gradlew clean build
